;;;; package.lisp

(defpackage #:structlisp
  (:use #:cl)
  (:export
   ;; Deque
   #:deque
   #:make-deque
   #:deque-count
   #:deque-empty-p
   #:deque-capacity
   #:deque-total-weight
   #:deque-maximum-count
   #:deque-maximum-weight
   #:deque-weight-function
   #:deque-eviction-end
   #:deque-ref
   #:deque-front
   #:deque-back
   #:deque-push-front
   #:deque-push-back
   #:deque-pop-front
   #:deque-pop-back
   #:deque-insert
   #:deque-remove-at
   #:deque-split-at
   #:deque-clear
   #:deque->vector
    #:deque->list
    #:deque-position
    #:deque-find
    #:deque-delete
    #:deque-append
    #:deque-move-all
   #:deque-error
   #:deque-error-deque
   #:deque-index-error
   #:deque-index-error-index
   #:deque-index-error-minimum
   #:deque-index-error-maximum
   #:deque-empty-error
   #:deque-weight-error
   #:deque-weight-error-element
   #:deque-weight-error-weight
   ;; Priority queue
   #:priority-queue
   #:make-priority-queue
   #:priority-queue-count
   #:priority-queue-empty-p
   #:priority-queue-push
   #:priority-queue-peek
   #:priority-queue-pop
   #:priority-queue-cancel
   #:priority-queue-change-priority
   #:priority-queue-clear
   #:top-k
   #:priority-queue-error
   #:priority-queue-error-queue
   #:priority-queue-duplicate-key
   #:priority-queue-duplicate-key-key
   ;; Sorted string index
   #:sorted-string-index
   #:make-sorted-string-index
   #:sorted-string-index-count
   #:sorted-string-index-empty-p
   #:sorted-string-index-ref
   #:sorted-string-index-key-ref
   #:sorted-string-index-lower-bound
   #:sorted-string-index-upper-bound
   #:sorted-string-index-equal-range
   #:sorted-string-index-prefix-range
   #:sorted-string-index-prefix-items
   #:sorted-string-index-insert
   #:sorted-string-index-remove-at
   #:sorted-string-index-remove
   #:sorted-string-index->vector
   #:sorted-string-index-error
   #:sorted-string-index-error-index
   #:sorted-string-index-key-error
   #:sorted-string-index-key-error-item
   #:sorted-string-index-key-error-key
   ;; Ordered map
   #:ordered-map
   #:make-ordered-map
   #:ordered-map-count
   #:ordered-map-empty-p
   #:ordered-map-get
   #:ordered-map-set
   #:ordered-map-delete
   #:ordered-map-first
   #:ordered-map-last
   #:ordered-map-pop-first
   #:ordered-map-pop-last
   #:ordered-map-move-to-front
   #:ordered-map-move-to-back
   #:ordered-map-map
   #:ordered-map-keys
   #:ordered-map-values
   #:ordered-map->alist
   #:ordered-map-clear
   ;; LRU and memo caches
   #:lru-cache
   #:make-lru-cache
   #:lru-cache-count
   #:lru-cache-empty-p
   #:lru-cache-total-weight
   #:lru-cache-maximum-count
   #:lru-cache-maximum-weight
   #:lru-cache-get
   #:lru-cache-peek
   #:lru-cache-put
   #:lru-cache-delete
   #:lru-cache-least-recent
   #:lru-cache-most-recent
   #:lru-cache-map
   #:lru-cache-keys
   #:lru-cache-clear
   #:lru-cache-error
   #:lru-cache-error-cache
   #:lru-cache-weight-error
   #:lru-cache-weight-error-key
   #:lru-cache-weight-error-value
   #:lru-cache-weight-error-weight
   #:memo-cache
   #:make-memo-cache
   #:memo-cache-count
   #:memo-cache-get
   #:memo-cache-delete
   #:memo-cache-clear
   ;; Integer intervals
   #:integer-interval
   #:make-integer-interval
   #:integer-interval-start
   #:integer-interval-end
   #:integer-interval-entry
   #:integer-interval-entry-start
   #:integer-interval-entry-end
   #:integer-interval-entry-value
   #:integer-interval-error
   #:integer-interval-error-start
   #:integer-interval-error-end
   #:integer-interval-set
   #:make-integer-interval-set
   #:integer-interval-set-count
   #:integer-interval-set-empty-p
   #:integer-interval-set-add
   #:integer-interval-set-remove
   #:integer-interval-set-contains-p
   #:integer-interval-set-covers-p
   #:integer-interval-set-intersects-p
   #:integer-interval-set-union
   #:integer-interval-set-intersection
   #:integer-interval-set-difference
   #:integer-interval-set->vector
   #:integer-interval-set-clear
   #:integer-interval-map
   #:make-integer-interval-map
   #:integer-interval-map-count
   #:integer-interval-map-empty-p
   #:integer-interval-map-get
   #:integer-interval-map-set
   #:integer-interval-map-delete
   #:integer-interval-map-overlaps
   #:integer-interval-map-map
   #:integer-interval-map->vector
   #:integer-interval-map-clear
   ;; Monotone integer index
   #:monotone-integer-index
   #:make-monotone-integer-index
   #:monotone-integer-index-count
   #:monotone-integer-index-empty-p
   #:monotone-integer-index-ref
   #:monotone-integer-index-append
   #:monotone-integer-index-lower-bound
   #:monotone-integer-index-upper-bound
   #:monotone-integer-index-find
   #:monotone-integer-index-before
   #:monotone-integer-index-at-or-before
   #:monotone-integer-index-at-or-after
   #:monotone-integer-index-after
   #:monotone-integer-index-range
   #:monotone-integer-index->vector
   #:monotone-integer-index-clear
   #:monotone-integer-index-error
   #:monotone-integer-index-error-index
   #:monotone-integer-index-order-error
   #:monotone-integer-index-order-error-value
   #:monotone-integer-index-order-error-last-value
   #:monotone-integer-index-value-error
   #:monotone-integer-index-value-error-value
   #:monotone-integer-index-value-error-maximum
   ;; Tests
   #:run-tests))

(in-package #:structlisp)
